name = "p"
compatibility_date = "2025-04-24"

workers_dev = false
main = "worker/index.ts"

[[rules]]
type = "Text"
globs = [ "**/*.html", "**/*.md" ]
fallthrough = true

[assets]
directory = "dist/frontend"
run_worker_first = true
binding = "ASSETS"

[triggers]
# clean r2 garbage every day
crons = ["0 */6 * * *"]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[observability]
enabled = true

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "p.787a68.de/*"
zone_name = "787a68.de"
workers_dev = false

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "e2339660faa34ece979e5ce468b5d0c3"  # id of your KV namespace

[[r2_buckets]]
binding = "R2"  # do not touch this
bucket_name = "pastebin-worker"  # bucket name of your R2 bucket

[vars]
# must be consistent with your routes
DEPLOY_URL = "https://p.787a68.de"

# url to repo, displayed in the index page
REPO = "https://github.com/787a68/pastebin-worker"

# the page title displayed in index page
INDEX_PAGE_TITLE = "Pastebin Worker"

# the name displayed in TOS
TOS_MAINTAINER = "787a68"

# the email displayed in TOS
TOS_MAIL = "36852208+787a68@users.noreply.github.com"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for paste pages
CACHE_PASTE_AGE = 600

# Default expiration
DEFAULT_EXPIRATION = "1d"

# Max expiration
MAX_EXPIRATION = "30d"

# A collection of {username: password} pair
# Leave empty to disable auth
BASIC_AUTH = {}

# Files larger than this threshold will be stored in R2
R2_THRESHOLD = "20M"

# File larger than this will be denied
R2_MAX_ALLOWED = "2G"

# The following mimetypes will be converted to text/plain
DISALLOWED_MIME_FOR_PASTE = ["text/html", "audio/x-mpegurl"]
