name: Monthly Sync from upstream (goshujin)

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出当前仓库的默认分支（无需指定 ref）
      - uses: actions/checkout@v4

      # 2. 检出上游仓库的 goshujin 分支
      - uses: actions/checkout@v4
        with:
          repository: SharzyL/pastebin-worker
          ref: goshujin
          path: upstream

      # 3. 同步文件并排除 wrangler.toml
      - run: |
          rsync -a --delete --exclude='wrangler.toml' upstream/ .

      # 4. 提交并推送到默认分支
      - run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "chore: Monthly sync from upstream (goshujin)"
          git push
