name: Monthly Sync from Upstream

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出自己仓库的默认分支
      - name: Checkout this repo
        uses: actions/checkout@v4

      # 2. 检出上游仓库的默认分支（公开仓库无需 token）
      - name: Checkout upstream repo
        uses: actions/checkout@v4
        with:
          repository: SharzyL/pastebin-worker
          path: upstream

      # 3. 删除不想要的文件
      - name: Remove upstream config & workflows
        run: |
          rm -f upstream/wrangler.toml
          rm -rf upstream/.github/workflows

      # 4. 拷贝剩余内容到工作区
      - name: Copy upstream content
        run: |
          cp -a upstream/. .

      # 5. 提交并推送（仅当有变更时）
      - name: Commit & Push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "chore: sync from upstream"
          git push
