name: Monthly Sync from Upstream

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone upstream repo
        run: |
          git clone --depth=1 https://github.com/SharzyL/pastebin-worker.git upstream

      - name: Remove unwanted files from upstream
        run: |
          rm -f upstream/wrangler.toml
          rm -rf upstream/.github/workflows

      - name: Copy upstream content
        run: |
          cp -a upstream/. .

      - name: Commit & Push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "chore: sync from upstream"
          git push
