name: Monthly Sync from Upstream

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出自己仓库的默认分支（全量历史）
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 克隆上游仓库到 upstream/
      - name: Clone upstream repo
        run: |
          git clone --depth=1 https://github.com/SharzyL/pastebin-worker.git upstream

      # 3. 删除上游不需要的文件，并清理本仓库已删文件
      - name: Prune unwanted and clean local deletions
        run: |
          # 删除 upstream 里不需要的配置、workflow、.git
          rm -f upstream/wrangler.toml
          rm -rf upstream/.github/workflows
          rm -rf upstream/.git

          # 删除根目录除 .git、.github、upstream 外的所有文件
          find . -maxdepth 1 \
            ! -name . \
            ! -name .git \
            ! -name .github \
            ! -name upstream \
            ! -name wrangler.toml \
            -exec rm -rf {} +

      # 4. 拷贝 upstream 里剩余文件到根目录，并删除 upstream/
      - name: Copy upstream content & cleanup
        run: |
          cp -a upstream/. .
          rm -rf upstream

      # 5. 提交并推送（仅当有变更时）
      - name: Commit & Push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to push"
          else
            git commit -m "chore: sync from upstream"
            git pull --rebase origin main
            git push
          fi
